version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'America/New_York'
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'America/New_York'
